services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: thetrader-id-app
    container_name: thetrader-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - thetrader-network
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: thetrader-web
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - thetrader-network
    depends_on:
      - app

  proxy:
    image: nginx:alpine
    container_name: thetrader-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/proxy/conf.d:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - thetrader-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: thetrader-certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: mysql:8.0
    container_name: thetrader-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - thetrader-network

  redis:
    image: redis:alpine
    container_name: thetrader-redis
    restart: unless-stopped
    networks:
      - thetrader-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    container_name: thetrader-queue
    restart: unless-stopped
    command: "php artisan queue:work --tries=3 --timeout=90"
    volumes:
      - ./:/var/www
    networks:
      - thetrader-network
    depends_on:
      - app
      - db
      - redis

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    container_name: thetrader-scheduler
    restart: unless-stopped
    command: "php artisan schedule:work"
    volumes:
      - ./:/var/www
    networks:
      - thetrader-network
    depends_on:
      - app
      - db
      - redis

networks:
  thetrader-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
